name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
          cache: true
      - run: go test -race ./...
      - run: go vet ./...
      - run: go build ./cmd/policedoc
      - name: Check go install
        run: |
          GOBIN="$RUNNER_TEMP/bin" go install ./cmd/policedoc
          "$RUNNER_TEMP/bin/policedoc" version

  nix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31
      - run: nix flake check
      - run: nix build .#policedoc
      - run: ./result/bin/policedoc version
